---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: app
          image: ghcr.io/au2001/gitops-demo:fa4482c
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
