apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: demo-app
  secretRef:
    name: flux-system
  url: https://github.com/au2001/gitops-demo.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-app
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: demo-app
  targetNamespace: apps
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: demo-app
