apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: demo-app
  namespace: apps-sync
spec:
  imageRepositoryRef:
    name: demo-app
  policy:
    numerical:
      order: asc
  filterTags:
    extract: $ts
