apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: podinfo-updates
  namespace: apps-sync
spec:
  git:
    push:
      branch: prd-podinfo-update
  update:
    path: ./production/podinfo
