apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
spec:
  patches:
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: HTTPS_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: HTTP_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: FTP_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: NO_PROXY
            value: "localhost,127.0.0.1"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: https_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: http_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: ftp_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: no_proxy
            value: "localhost,127.0.0.1"
      target:
        kind: Deployment
        name: source-controller
        namespace: flux-system
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: HTTPS_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: HTTP_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: FTP_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: NO_PROXY
            value: "localhost,127.0.0.1"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: https_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: http_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: ftp_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: no_proxy
            value: "localhost,127.0.0.1"
      target:
        kind: Deployment
        name: kustomize-controller
        namespace: flux-system
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: HTTPS_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: HTTP_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: FTP_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: NO_PROXY
            value: "localhost,127.0.0.1"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: https_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: http_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: ftp_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: no_proxy
            value: "localhost,127.0.0.1"
      target:
        kind: Deployment
        name: helm-controller
        namespace: flux-system
    - patch: |
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: HTTPS_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: HTTP_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: FTP_PROXY
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: NO_PROXY
            value: "localhost,127.0.0.1"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: https_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: http_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: ftp_proxy
            value: "http://160.92.223.1:443"
        - op: add
          path: /spec/template/spec/containers/0/env/-
          value:
            name: no_proxy
            value: "localhost,127.0.0.1"
      target:
        kind: Deployment
        name: notification-controller
        namespace: flux-system
