apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: teams
  namespace: flux-system
spec:
  interval: 30s
  path: ./teams/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
