apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  path: ./apps/podinfo/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: apps

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  path: ./apps/podinfo/updates/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
