apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: app-manifests
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: app-manifests
  url: https://github.com/au2001/gitops-demo.git
