apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-sync
  namespace: flux-system
spec:
  interval: 30s
  prune: true
  sourceRef:
    kind: GitRepository
    name: app-manifests
