name: Automatic PR on podinfo update
on:
  push:
    branches:
    - podinfo-update

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Parse podinfo version
      id: parse
      run: |
        IMAGE=$(sed -n 's/^\s*image: \(ghcr\.io\/stefanprodan\/podinfo:.*\) #.*$/\1/p' ./apps/podinfo/deployment.yaml)
        VERSION=$(sed -n 's/^ghcr\.io\/stefanprodan\/podinfo:\(.*\)$/\1/p' <<< $IMAGE)

        echo ::set-output name=IMAGE::$IMAGE
        echo ::set-output name=VERSION::$VERSION

    - name: Create pull request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: main
        pr_title: "Update podinfo to ${{ steps.parse.outputs.VERSION }}"
        pr_body: "Changes the podinfo container image to ${{ steps.parse.outputs.IMAGE }}"
        pr_label: "auto-update"
        pr_reviewer: au2001
        github_token: ${{ secrets.GITHUB_TOKEN }}
